<?php

namespace App\Exports;

use App\Invest;
use Illuminate\Contracts\Queue\ShouldQueue;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromQuery;

class InvestExportFromQuery implements FromQuery, ShouldQueue
{
	use Exportable;

	public function query()
	{
		return Invest::query()->select(
			'card_id',
			'passport',
			'hn',
			'first_name',
			'last_name',
			'sex',
			'age',
			'age_month',
			'age_days',
			'nation',
			'occupation',
			'occupation_oth',
			'work_office',
			'work_contact',
			'work_phone',
			'sick_stay_type',
			'sick_stay_type_other',
			'sick_house_no',
			'sick_village_no',
			'sick_village',
			'sick_lane',
			'sick_road',
			'sick_province',
			'sick_district',
			'sick_sub_district',
			'data3_3chk',
			'data3_3chk_lung',
			'data3_3chk_heart',
			'data3_3chk_cirrhosis',
			'data3_3chk_kidney',
			'data3_3chk_diabetes',
			'data3_3chk_blood',
			'data3_3chk_immune',
			'data3_3chk_anaemia',
			'data3_3chk_cerebral',
			'data3_3chk_pregnant',
			'data3_3chk_fat',
			'data3_3chk_cancer',
			'data3_3chk_cancer_name',
			'data3_3chk_other',
			'data3_3input_other',
			'data3_1date_sickdate',
			'sick_province_first',
			'sick_district_first',
			'sick_sub_district_first',
			'treat_first_date',
			'treat_first_province',
			'treat_first_district',
			'treat_first_sub_district',
			'treat_first_hospital',
			'treat_place_province',
			'treat_place_district',
			'treat_place_sub_district',
			'treat_place_hospital',
			'fever_history',
			'body_temperature_first',
			'oxygen_saturate',
			'sym_cough',
			'sym_sore',
			'sym_muscle',
			'sym_snot',
			'sym_sputum',
			'sym_breathe',
			'sym_headache',
			'sym_diarrhoea',
			'sym_other',
			'sym_othertext',
			'breathing_tube_chk',
			'breathing_tube_date',
			'lab_cxr1_chk',
			'lab_cxr1_date',
			'lab_cxr1_result',
			'lab_cxr1_detail',
			'lab_cxr1_file',
			'lab_cbc_date',
			'lab_cbc_hb',
			'lab_cbc_hct',
			'lab_cbc_platelet_count',
			'lab_cbc_wbc',
			'lab_cbc_neutrophil',
			'lab_cbc_lymphocyte',
			'lab_cbc_atyp_lymph',
			'lab_cbc_mono',
			'lab_cbc_other',
			'lab_rapid_test_method',
			'lab_rapid_test_date',
			'lab_rapid_test_result',
			'lab_rapid_test_pathogen_flu_a',
			'lab_rapid_test_pathogen_flu_b',
			'lab_sars_cov2_no_1_date',
			'lab_sars_cov2_no_1_specimen',
			'lab_sars_cov2_no_1_lab',
			'lab_sars_cov2_no_1_result',
			'lab_sars_cov2_no_2_date',
			'lab_sars_cov2_no_2_specimen',
			'lab_sars_cov2_no_2_lab',
			'lab_sars_cov2_no_2_result',
			'treat_patient_type',
			'treat_place_date',
			'first_diag',
			'covid19_drug_medicate',
			'covid19_drug_medicate_first_date',
			'covid19_drug_medicate_name',
			'covid19_drug_medicate_name_other',
			'patient_treat_status',
			'patient_treat_status_other',
			'risk_detail',
			'risk_type',
			'risk_type_text',
			'risk_stay_outbreak_chk',
			'risk_stay_outbreak_country',
			'risk_stay_outbreak_city',
			'risk_stay_outbreak_city_other',
			'risk_stay_outbreak_arrive_date',
			'risk_stay_outbreak_arrive_thai_date',
			'risk_stay_outbreak_airline',
			'risk_stay_outbreak_flight_no',
			'risk_stay_outbreak_seat_no',
			'risk_stay_outbreak_province',
			'risk_stay_outbreak_district',
			'risk_stay_outbreak_sub_district',
			'risk_treat_or_visit_patient',
			'risk_care_flu_patient',
			'risk_contact_covid_19',
			'risk_contact_covid_19_patient_name',
			'risk_contact_covid_19_sat_id',
			'risk_contact_covid_19_touch',
			'risk_contact_covid_19_duration',
			'risk_contact_tourist',
			'risk_travel_to_arena',
			'risk_travel_arena_name',
			'be_patient_cluster',
			'be_patient_critical_unknown_cause',
			'be_health_personel',
			'risk_other',
			'entry_user',
			'pt_status'

		)->where('id', '<=', 100);
	}
}
